module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        root: ['./src'],
        extensions: ['.ios.js', '.android.js', '.js', '.ts', '.tsx', '.json'],
        alias: {
          '@app/features/*': ['./src/features/*'],
          '@app/features': ['./src/features'],
          '@app/components/*': ['./src/components/*'],
          '@app/components': ['./src/components'],
          '@app/navigator/*': ['./src/navigator/*'],
          '@app/navigator': ['./src/navigator'],
          '@app/screens/*': ['./src/screens/*'],
          '@app/screens': ['./src/screens'],
          '@app/services/*': ['./src/services/*'],
          '@app/services': ['./src/services'],
          '@app/styles/*': ['./src/styles/*'],
          '@app/styles': ['./src/styles'],
          '@app/lib/*': ['./src/lib/*'],
          '@app/lib': ['./src/lib'],
          '@app/config/*': ['./src/config/*'],
          '@app/config': ['./src/config'],
          '@app/theme': ['./src/config/theme'],
          '@app/assets/*': ['./src/assets/*'],
          '@app/assets': ['./src/assets'],
          '@app/store/*': ['./src/store/*'],
          '@app/store': ['./src/store'],
          '@app/api/*': ['./src/api/*'],
          '@app/api': ['./src/api'],
          '@app/hooks/*': ['./src/hooks/*'],
          '@app/hooks': ['./src/hooks'],
          '@app/validators/*': ['./src/validators/*'],
          '@app/validators': ['./src/validators'],
        },
      },
    ],
  ],
};
